"""Add photo model

Revision ID: 0eee6e916147
Revises: 312adc41ccaf
Create Date: 2022-01-04 23:03:45.734542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0eee6e916147"
down_revision = "312adc41ccaf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "photos",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("blob_path", sa.String(length=255), nullable=False),
        sa.Column(
            "model_type",
            sa.Enum("LUNG_CANCER", "PNEUMONIA", "BRAIN_TUMOUR", name="customvisionmodels"),
            nullable=False,
        ),
        sa.Column("model_result", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("photos")
    # ### end Alembic commands ###
